// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDy20iz2TsYrk4n5iP_ZX37tDthqFxFIrc',
    appId: '1:911932195497:web:88a134dec44ea20fc2dfb8',
    messagingSenderId: '911932195497',
    projectId: 'todolist-305cc',
    authDomain: 'todolist-305cc.firebaseapp.com',
    storageBucket: 'todolist-305cc.appspot.com',
    measurementId: 'G-4903NYPBXD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxbs8oTtjkQRvN1sDZIG5L7uGa0f1b7aI',
    appId: '1:911932195497:android:3e17df4340e14cd4c2dfb8',
    messagingSenderId: '911932195497',
    projectId: 'todolist-305cc',
    storageBucket: 'todolist-305cc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZ67v9TooYwRtMkGLtt5yOu2Fu2-cXB-I',
    appId: '1:911932195497:ios:284e29f7f6c7181ec2dfb8',
    messagingSenderId: '911932195497',
    projectId: 'todolist-305cc',
    storageBucket: 'todolist-305cc.appspot.com',
    iosClientId: '911932195497-7ihlekg8jovs39qscssfmmjft2jpug7n.apps.googleusercontent.com',
    iosBundleId: 'com.moon.todolist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZ67v9TooYwRtMkGLtt5yOu2Fu2-cXB-I',
    appId: '1:911932195497:ios:284e29f7f6c7181ec2dfb8',
    messagingSenderId: '911932195497',
    projectId: 'todolist-305cc',
    storageBucket: 'todolist-305cc.appspot.com',
    iosClientId: '911932195497-7ihlekg8jovs39qscssfmmjft2jpug7n.apps.googleusercontent.com',
    iosBundleId: 'com.moon.todolist',
  );
}
